M48
; DRILL file {KiCad (6.0.9-0)} date 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-19T19:17:51-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X0.75Y-1.0134
X0.75Y-1.1866
T2
X1.5445Y-1.2244
X1.7355Y-1.2244
T3
X1.5327Y-1.1051
X1.7473Y-1.1051
T0
M30
