M48
; DRILL file {KiCad 7.0.8} date 2023 November 29, Wednesday 08:53:46
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-29T08:53:46-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X1.3585Y-0.6884
X1.5495Y-0.6884
T2
X1.3467Y-0.5691
X1.5613Y-0.5691
T0
M30
